import type { Metadata } from "next";
import {Inconsolata, Karla} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";

const karla = Karla({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-karla',
})

const inconsolata = Inconsolata({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inconsolata',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={`${inconsolata.variable} ${karla.variable}`}>
      <body className={"max-w-4xl mx-auto p-5 sm:p-10"}>{children}</body>
    </html>
  );
}
